### ISSUE TITLE
 Why did externalPulsar authParmas make this mistake?

### ISSUE THREAD

**Issue by 1191510903** [zilliztech/milvus-helm#102]
externalPulsar:
  enabled: true
  host: "xxxx"
  port: 30012
  maxMessageSize: "5242880"  # 5 * 1024 * 1024 Bytes, Maximum size of each message in pulsar.
  tenant: "xxxx"
  namespace: "xxx"
  authPlugin: "org.apache.pulsar.client.impl.auth.AuthenticationToken"
  authParams: {"token": "eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJsbG0tcGxhdGZvcm0tdG9rZW4ifQ.g4cejYFJtfUlPHbeOdmNRjMlNWImhvLkcF-YR71YpPjiXihqCTOM4vghlRIDYECR4Oc7xxxxxx"}
看源码发现是go解析jwt没有解析出来，是否有解决方案呢？
![image](https://github.com/zilliztech/milvus-helm/assets/55501552/e7f59b5a-f073-41dd-8551-f5940120ab52)

**Comment by haorenfsa** [comment]
JSON format is also supported in yaml,@1191510903 
When you write
```yaml
authParams: {"token": "eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJsbG0tcGxhdGZvcm0tdG9rZW4ifQ.g4cejYFJtfUlPHbeOdmNRjMlNWImhvLkcF-YR71YpPjiXihqCTOM4vghlRIDYECR4Oc7xxxxxx"}
```

it's same as
```yaml
authParams:
  token: eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJsbG0tcGxhdGZvcm0tdG9rZW4ifQ.g4cejYFJtfUlPHbeOdmNRjMlNWImhvLkcF-YR71YpPjiXihqCTOM4vghlRIDYECR4Oc7xxxxxx
```

So instead you should write, that's what milvus is expecting
```yaml
authParams: '{"token":"eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJsbG0tcGxhdGZvcm0tdG9rZW4ifQ.g4cejYFJtfUlPHbeOdmNRjMlNWImhvLkcF-YR71YpPjiXihqCTOM4vghlRIDYECR4Oc7xxxxxx"}'
```

You can verify the result in any online formatter, like https://jsonformatter.org/yaml-to-json
