### ISSUE TITLE
Milvus-helm-release for milvus-2.3.17 or milvus-2.3.18

### ISSUE THREAD

**Issue by akmalmasud96** [zilliztech/milvus-helm#106]
I want to ask that is there any update or expected-date for the milvus-helm-release for [milvus-2.3.17](https://github.com/milvus-io/milvus/releases/tag/v2.3.17) or [milvus-2.3.18](https://github.com/milvus-io/milvus/releases/tag/v2.3.18).

**Comment by haorenfsa** [comment]
Hi @akmalmasud96, the default Milvus image version will only be updated by MIlvus v2.4.x. You can use newest release to install v2.3.x by setting the `image.all.tag` field in values.
