### ISSUE TITLE
There is no version 4.2.1 in the Helm repository.

### ISSUE THREAD

**Issue by atuk721** [zilliztech/milvus-helm#111]
In [the Release page](https://github.com/zilliztech/milvus-helm/releases), milvus-4.2.1 is released.
But in [the Helm repository](https://artifacthub.io/packages/helm/milvus-helm/milvus), up to version 4.2.0 is released.

**Comment by haorenfsa** [comment]
Hi @atuk721, thank you for pointing this out. I'll look on this.

**Comment by haorenfsa** [comment]
I uploaded it manually. aritfacthub will be auto updated soon. Thank you again!

**Comment by atuk721** [comment]
Hi @haorenfsa, I've confirmed Artifact HUB's version is updated.
Thank you for your quick response!
