### ISSUE TITLE
Ingress. AWS lb controller

### ISSUE THREAD

**Issue by AndreiPaulau** [zilliztech/milvus-helm#30]
Gents,

Don't know why this wasn't requested earlier, may be there is justification, but

Would you be so kind to adapt Ingress to support https://kubernetes-sigs.github.io/aws-load-balancer-controller/
Since ALB supports GRPC backend protocol from the box https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html#target-group-protocol-version

**Comment by haorenfsa** [comment]
Hi @AndreiPaulau.  Plz check if this doc solves your problem https://milvus.io/docs/gcp_layer7.md

**Comment by AndreiPaulau** [comment]
Hello, that is applicable for GCP
In AWS i've managed this by bringing up Layer 4 Classic LB to use pure TCP
