### ISSUE TITLE
milvus LOAD API not functioning as expected with the helm-charts

### ISSUE THREAD

**Issue by shaiktas** [zilliztech/milvus-helm#34]
Milvus Version:  2.3.1
Exeucuting below operation on milvus Client using JAVA Client
```
1. CreatedCollection with 4 fields
2. Inserted 10 elements/entries into a  collection created in Step 1
3. CreatedIndex
4. Loading Collection
 The Load collection API is struck and after some time it finishing, but load is not performed. From Attu UI it intitially displyed as 50%, after Load API finish execution, it it visiable as unloaded.  
```
Attaching here 
Attaching queryNode logs for reference:
[milvus-querynodelogs-loadAPI.txt](https://github.com/milvus-io/milvus/files/13234115/milvus-querynodelogs-loadAPI.txt)

Attu UI.

<img width="1329" alt="Screenshot 2023-11-01 at 11 00 16 PM" src="https://github.com/milvus-io/milvus/assets/52338042/9f96da55-4d24-41fd-9304-05dd5755a860">
<img width="1427" alt="Screenshot 2023-11-02 at 9 27 02 AM" src="https://github.com/milvus-io/milvus/assets/52338042/3fd1e183-3014-4d72-b849-046c1241a4a5">
[milvus-querycoorlogs-loadAPI-0211.txt](https://github.com/milvus-io/milvus/files/13240874/milvus-querycoorlogs-loadAPI-0211.txt)
[milvus-querynodelogs-loadAPI-0211.txt](https://github.com/milvus-io/milvus/files/13240881/milvus-querynodelogs-loadAPI-0211.txt)

[javaClientAPI.txt](https://github.com/milvus-io/milvus/files/13234122/javaClientAPI.txt)

**Comment by haorenfsa** [comment]
it seems a milvus issue.

**Comment by haorenfsa** [comment]
I copied this issue to milvus https://github.com/milvus-io/milvus/issues/30212. feel free to reopen it if you think this is milvus-helm's issue.

**Comment by shaiktas** [comment]
@haorenfsa pls close this, it is fixed after applying rootPath a string value. The issue was existed with empty rootPath under storage config
