### ISSUE TITLE
etcd arm64 supported for milvus v2.3.3

### ISSUE THREAD

**Issue by simonwei97** [zilliztech/milvus-helm#36]
## Backgroud

Milvus supported x86 and ARM, which started from version `v2.3.0`. 

Branch master milvus version is `v2.3.3`, and etcd dependency version is `3.5.5-r2`, which on dockerhub repository `"milvusdb/etcd"`

milvus v2.3.2 has x86 and ARM images.

https://hub.docker.com/r/milvusdb/milvus/tags?page=1&name=2.3.2
![image](https://github.com/zilliztech/milvus-helm/assets/119845914/8b448e0a-4326-4f2c-8996-54b7488f3709)

But `milvusdb/etcd` only has x86 images, ARM image is not exist.

https://hub.docker.com/r/milvusdb/etcd/tags?page=1&name=3.5.5-r2
![image](https://github.com/zilliztech/milvus-helm/assets/119845914/17e70b0a-022f-4181-8136-2e11851db860)

---

I found that repo `bitnami/etcd` supports x86 and ARM for `3.5.7`, while both `3.5.5` and `3.5.6` do not supports.

https://hub.docker.com/r/bitnami/etcd/tags?page=1&name=3.5.7

https://hub.docker.com/r/bitnami/etcd/tags?page=1&name=3.5.5
https://hub.docker.com/r/bitnami/etcd/tags?page=1&name=3.5.6

##  Approche
If it's possible to upgrade etcd version from `3.5.5` to `3.5.7` for milvus `v2.3.3`, which can supports both x86 and ARM arch ?

> Attention: Maybe we should check milvus helm chart v2.3.0, v2.3.1, v2.3.2 for this same problem.

**Comment by richxnh** [comment]
Hello, have you solved the issue with etcd arm64 version 3.5.5? Thank you.

**Comment by haorenfsa** [comment]
Solved in #51 . use the newest chart, or you can update the etcd image tag to `milvusdb/etcd:3.5.5-r4`

**Comment by simonwei97** [comment]
Thanks.
