### ISSUE TITLE
Azure Storage, Support Workload Identity

### ISSUE THREAD

**Issue by michelefa1988** [zilliztech/milvus-helm#52]
Azur added Azure Workload Identities (see https://github.com/Azure/azure-workload-identity and https://azure.github.io/azure-workload-identity/docs/) to AKS. The functionality is stable and is the recommended approach for production situations.

AWI is essentially the equivalent of AWS's IAM Roles for Service Accounts and works the same. I.e, your cluster becomes an OIDC identity provider and a specific service account in a specific namespace can be designated as federated principal to which Azure IAM roles can be attached. This is significantly more secure than using credentials (StorageAccountName + secret)

Can you please make minio support this?

**Comment by haorenfsa** [comment]
It's supported already, check this doc https://milvus.io/docs/abs.md

**Comment by michelefa1988** [comment]
Ahhh, thanks I see. I was looking at the data storage section
