### ISSUE TITLE
docker.io prefix for etcd

### ISSUE THREAD

**Issue by arkim822** [zilliztech/milvus-helm#92]
Hello,

My company has a policy where we have to upload images to our internal artifactory via docker.

When trying to run our CICD pipeline, we noticed that the 'docker.io/' prefix was being appended to our internal ref.

Does anyone know why this is just for etcd and how we can remove the 'docker.io/' prefix?

**Comment by EastlingWoo** [comment]
You can try to add the parameter "--set etcd.image.registry=<artifactory>"
